version: "3.8"
services:

  db:
    image: mysql
    container_name: db_docker
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - dev
    depends_on:
     - www

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_docker
    restart: always
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
    networks:
      - dev

  redis:
    container_name: redis_docker
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    networks:
      - dev

  www:
    build: php
    container_name: www_docker
    depends_on:
      - redis
    ports:
      - "8741:80"
    volumes:
      - ./php/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
    restart: always
    networks:
      - dev

networks:
  dev:


volumes:
  db-data:
